# Variabili
CC = gcc
CFLAGS = -D_FILE_OFFSET_BITS=64 -static -pthread -lfuse -ldl
LDFLAGS = -shared -fPIC

# Target principali
all: exploit evil-so

# Compilazione di exploit.c
exploit: exploit.c
	$(CC) $(CFLAGS) exploit.c -o exploit

# Compilazione di evil-so.c
evil-so: evil-so.c
	$(CC) $(LDFLAGS) evil-so.c -o evil.so

# Pulizia dei file compilati
clean:
	rm -f exploit evil.so
